alter table move drop foreign key FKm752v1lw4h2m9rbjl923y35o8;
alter table pokemon_abilities drop foreign key FKi2j52hdb6cg5c4uwfk7hsfmi4;
alter table pokemon_abilities drop foreign key FKd4e0nwtlcear2rebo3kh7pqkp;
alter table pokemon_moves drop foreign key FKbqawqxii6j0ylbw7n5fwn8u4r;
alter table pokemon_moves drop foreign key FK39kw2ij1hox9c14g5sinxrt8j;
alter table pokemon_types drop foreign key FKn7hpi4p9jx1jxe0k0unc7exad;
alter table pokemon_types drop foreign key FK2mg61es8piwhjsf2184rqxf1y;
drop table if exists ability;
drop table if exists item;
drop table if exists move;
drop table if exists pokemon;
drop table if exists pokemon_abilities;
drop table if exists pokemon_moves;
drop table if exists pokemon_types;
drop table if exists type;
